# Gemfile

source "https://rubygems.org"

gem "rails", "~> 8.1.3", ">= 8.1.3.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false

# MongoDB and CORS integration
gem "mongoid", "~> 9.0"
gem "rack-cors", require: "rack/cors"

group :development, :test do
  gem "dotenv-rails"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end